In [2]:
import pandas as pd
from sklearn.feature_extraction import DictVectorizer
from sklearn.linear_model import LinearRegression
from sklearn.metrics import root_mean_squared_error

In [3]:
filename_jan = "https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2026-01.parquet"
filename_feb = "https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2026-02.parquet"

In [4]:
df = pd.read_parquet(filename_jan)

In [5]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,2,2026-01-01 00:54:04,2026-01-01 00:59:37,1.0,0.97,1.0,N,239,238,1,7.2,1.00,0.5,3.66,0.0,1.0,15.86,2.5,0.0,0.00
1,1,2026-01-01 00:34:04,2026-01-01 00:39:47,0.0,0.90,1.0,N,163,162,2,7.9,4.25,0.5,0.00,0.0,1.0,13.65,2.5,0.0,0.75
2,1,2026-01-01 00:57:06,2026-01-01 01:05:59,0.0,1.40,1.0,N,43,237,1,10.7,4.25,0.5,2.50,0.0,1.0,18.95,2.5,0.0,0.75
3,2,2026-01-01 00:15:22,2026-01-01 00:58:10,4.0,5.58,1.0,N,142,209,1,38.7,1.00,0.5,11.11,0.0,1.0,55.56,2.5,0.0,0.75
4,2,2026-01-01 00:27:13,2026-01-01 00:40:43,0.0,2.16,1.0,N,88,144,1,13.5,1.00,0.5,3.85,0.0,1.0,23.10,2.5,0.0,0.75

In [6]:
Q1 = df.shape

In [7]:
Q1

(3724889, 20)

In [8]:
df.tpep_dropoff_datetime = pd.to_datetime(df.tpep_dropoff_datetime)
df.tpep_pickup_datetime = pd.to_datetime(df.tpep_pickup_datetime)

df['duration'] = df.tpep_dropoff_datetime - df.tpep_pickup_datetime

df.duration = df.duration.apply( lambda td: td.total_seconds() / 60)

In [9]:
std = df['duration'].std()

In [10]:
Q2 = std

In [11]:
Q2

np.float64(25.17801981831615)

In [12]:
old_len = len(df)
df = df[((df.duration >= 1) & (df.duration <= 60))]
n_len = len(df)

In [13]:
Q3 = n_len / old_len

In [14]:
Q3

0.958934346768454

In [15]:
dict = DictVectorizer()

In [16]:
categorical = ['PULocationID', 'DOLocationID']
df[categorical] = df[categorical].astype(str)

train_dict = df[categorical].to_dict(orient='records')

In [17]:
train_dict

[{'PULocationID': '239', 'DOLocationID': '238'},
 {'PULocationID': '163', 'DOLocationID': '162'},
 {'PULocationID': '43', 'DOLocationID': '237'},
 {'PULocationID': '142', 'DOLocationID': '209'},
 {'PULocationID': '88', 'DOLocationID': '144'},
 {'PULocationID': '144', 'DOLocationID': '137'},
 {'PULocationID': '142', 'DOLocationID': '50'},
 {'PULocationID': '50', 'DOLocationID': '234'},
 {'PULocationID': '161', 'DOLocationID': '45'},
 {'PULocationID': '237', 'DOLocationID': '263'},
 {'PULocationID': '161', 'DOLocationID': '144'},
 {'PULocationID': '144', 'DOLocationID': '79'},
 {'PULocationID': '163', 'DOLocationID': '48'},
 {'PULocationID': '234', 'DOLocationID': '90'},
 {'PULocationID': '161', 'DOLocationID': '229'},
 {'PULocationID': '162', 'DOLocationID': '170'},
 {'PULocationID': '90', 'DOLocationID': '87'},
 {'PULocationID': '90', 'DOLocationID': '41'},
 {'PULocationID': '239', 'DOLocationID': '263'},
 {'PULocationID': '262', 'DOLocationID': '141'},
 {'PULocationID': '140', 'DOLocationID': '237'},
 {'PULocationID': '43', 'DOLocationID': '142'},
 {'PULocationID': '161', 'DOLocationID': '239'},
 {'PULocationID': '239', 'DOLocationID': '151'},
 {'PULocationID': '164', 'DOLocationID': '164'},
 {'PULocationID': '148', 'DOLocationID': '238'},
 {'PULocationID': '249', 'DOLocationID': '114'},
 {'PULocationID': '237', 'DOLocationID': '236'},
 {'PULocationID': '237', 'DOLocationID': '233'},
 {'PULocationID': '231', 'DOLocationID': '79'},
 {'PULocationID': '114', 'DOLocationID': '229'},
 {'PULocationID': '237', 'DOLocationID': '161'},
 {'PULocationID': '161', 'DOLocationID': '262'},
 {'PULocationID': '140', 'DOLocationID': '79'},
 {'PULocationID': '35', 'DOLocationID': '72'},
 {'PULocationID': '138', 'DOLocationID': '97'},
 {'PULocationID': '114', 'DOLocationID': '107'},
 {'PULocationID': '138', 'DOLocationID': '7'},
 {'PULocationID': '140', 'DOLocationID': '265'},
 {'PULocationID': '249', 'DOLocationID': '106'},
 {'PULocationID': '162', 'DOLocationID': '164'},
 {'PULocationID': '148', 'DOLocationID': '87'},
 {'PULocationID': '234', 'DOLocationID': '41'},
 {'PULocationID': '158', 'DOLocationID': '125'},
 {'PULocationID': '125', 'DOLocationID': '233'},
 {'PULocationID': '238', 'DOLocationID': '243'},
 {'PULocationID': '237', 'DOLocationID': '236'},
 {'PULocationID': '237', 'DOLocationID': '140'},
 {'PULocationID': '140', 'DOLocationID': '75'},
 {'PULocationID': '68', 'DOLocationID': '68'},
 {'PULocationID': '132', 'DOLocationID': '246'},
 {'PULocationID': '246', 'DOLocationID': '145'},
 {'PULocationID': '237', 'DOLocationID': '164'},
 {'PULocationID': '50', 'DOLocationID': '116'},
 {'PULocationID': '163', 'DOLocationID': '164'},
 {'PULocationID': '164', 'DOLocationID': '262'},
 {'PULocationID': '142', 'DOLocationID': '50'},
 {'PULocationID': '90', 'DOLocationID': '144'},
 {'PULocationID': '138', 'DOLocationID': '14'},
 {'PULocationID': '48', 'DOLocationID': '151'},
 {'PULocationID': '75', 'DOLocationID': '151'},
 {'PULocationID': '138', 'DOLocationID': '226'},
 {'PULocationID': '114', 'DOLocationID': '211'},
 {'PULocationID': '211', 'DOLocationID': '170'},
 {'PULocationID': '170', 'DOLocationID': '37'},
 {'PULocationID': '132', 'DOLocationID': '255'},
 {'PULocationID': '143', 'DOLocationID': '125'},
 {'PULocationID': '79', 'DOLocationID': '90'},
 {'PULocationID': '113', 'DOLocationID': '263'},
 {'PULocationID': '164', 'DOLocationID': '66'},
 {'PULocationID': '66', 'DOLocationID': '225'},
 {'PULocationID': '229', 'DOLocationID': '249'},
 {'PULocationID': '238', 'DOLocationID': '143'},
 {'PULocationID': '143', 'DOLocationID': '143'},
 {'PULocationID': '143', 'DOLocationID': '143'},
 {'PULocationID': '142', 'DOLocationID': '236'},
 {'PULocationID': '162', 'DOLocationID': '263'},
 {'PULocationID': '263', 'DOLocationID': '236'},
 {'PULocationID': '237', 'DOLocationID': '68'},
 {'PULocationID': '48', 'DOLocationID': '42'},
 {'PULocationID': '249', 'DOLocationID': '41'},
 {'PULocationID': '231', 'DOLocationID': '68'},
 {'PULocationID': '68', 'DOLocationID': '48'},
 {'PULocationID': '48', 'DOLocationID': '236'},
 {'PULocationID': '79', 'DOLocationID': '233'},
 {'PULocationID': '79', 'DOLocationID': '237'},
 {'PULocationID': '79', 'DOLocationID': '25'},
 {'PULocationID': '144', 'DOLocationID': '36'},
 {'PULocationID': '170', 'DOLocationID': '236'},
 {'PULocationID': '236', 'DOLocationID': '236'},
 {'PULocationID': '263', 'DOLocationID': '263'},
 {'PULocationID': '162', 'DOLocationID': '163'},
 {'PULocationID': '163', 'DOLocationID': '161'},
 {'PULocationID': '75', 'DOLocationID': '41'},
 {'PULocationID': '166', 'DOLocationID': '41'},
 {'PULocationID': '79', 'DOLocationID': '170'},
 {'PULocationID': '232', 'DOLocationID': '164'},
 {'PULocationID': '239', 'DOLocationID': '239'},
 {'PULocationID': '239', 'DOLocationID': '97'},
 {'PULocationID': '79', 'DOLocationID': '237'},
 {'PULocationID': '158', 'DOLocationID': '151'},
 {'PULocationID': '166', 'DOLocationID': '166'},
 {'PULocationID': '166', 'DOLocationID': '116'},
 {'PULocationID': '141', 'DOLocationID': '237'},
 {'PULocationID': '43', 'DOLocationID': '233'},
 {'PULocationID': '79', 'DOLocationID': '170'},
 {'PULocationID': '239', 'DOLocationID': '142'},
 {'PULocationID': '142', 'DOLocationID': '234'},
 {'PULocationID': '246', 'DOLocationID': '186'},
 {'PULocationID': '151', 'DOLocationID': '152'},
 {'PULocationID': '148', 'DOLocationID': '107'},
 {'PULocationID': '237', 'DOLocationID': '262'},
 {'PULocationID': '236', 'DOLocationID': '141'},
 {'PULocationID': '262', 'DOLocationID': '263'},
 {'PULocationID': '87', 'DOLocationID': '263'},
 {'PULocationID': '262', 'DOLocationID': '74'},
 {'PULocationID': '239', 'DOLocationID': '43'},
 {'PULocationID': '239', 'DOLocationID': '87'},
 {'PULocationID': '113', 'DOLocationID': '48'},
 {'PULocationID': '239', 'DOLocationID': '141'},
 {'PULocationID': '142', 'DOLocationID': '162'},
 {'PULocationID': '234', 'DOLocationID': '79'},
 {'PULocationID': '75', 'DOLocationID': '262'},
 {'PULocationID': '140', 'DOLocationID': '238'},
 {'PULocationID': '137', 'DOLocationID': '141'},
 {'PULocationID': '141', 'DOLocationID': '141'},
 {'PULocationID': '229', 'DOLocationID': '137'},
 {'PULocationID': '142', 'DOLocationID': '239'},
 {'PULocationID': '239', 'DOLocationID': '151'},
 {'PULocationID': '151', 'DOLocationID': '42'},
 {'PULocationID': '68', 'DOLocationID': '170'},
 {'PULocationID': '90', 'DOLocationID': '90'},
 {'PULocationID': '234', 'DOLocationID': '74'},
 {'PULocationID': '234', 'DOLocationID': '137'},
 {'PULocationID': '164', 'DOLocationID': '234'},
 {'PULocationID': '141', 'DOLocationID': '233'},
 {'PULocationID': '137', 'DOLocationID': '79'},
 {'PULocationID': '79', 'DOLocationID': '113'},
 {'PULocationID': '237', 'DOLocationID': '229'},
 {'PULocationID': '239', 'DOLocationID': '263'},
 {'PULocationID': '142', 'DOLocationID': '262'},
 {'PULocationID': '262', 'DOLocationID': '141'},
 {'PULocationID': '237', 'DOLocationID': '50'},
 {'PULocationID': '239', 'DOLocationID': '68'},
 {'PULocationID': '161', 'DOLocationID': '41'},
 {'PULocationID': '151', 'DOLocationID': '238'},
 {'PULocationID': '132', 'DOLocationID': '75'},
 {'PULocationID': '90', 'DOLocationID': '90'},
 {'PULocationID': '158', 'DOLocationID': '48'},
 {'PULocationID': '79', 'DOLocationID': '113'},
 {'PULocationID': '246', 'DOLocationID': '48'},
 {'PULocationID': '237', 'DOLocationID': '237'},
 {'PULocationID': '249', 'DOLocationID': '234'},
 {'PULocationID': '249', 'DOLocationID': '68'},
 {'PULocationID': '236', 'DOLocationID': '237'},
 {'PULocationID': '237', 'DOLocationID': '113'},
 {'PULocationID': '90', 'DOLocationID': '158'},
 {'PULocationID': '249', 'DOLocationID': '133'},
 {'PULocationID': '144', 'DOLocationID': '161'},
 {'PULocationID': '162', 'DOLocationID': '75'},
 {'PULocationID': '261', 'DOLocationID': '170'},
 {'PULocationID': '164', 'DOLocationID': '88'},
 {'PULocationID': '249', 'DOLocationID': '239'},
 {'PULocationID': '239', 'DOLocationID': '238'},
 {'PULocationID': '158', 'DOLocationID': '125'},
 {'PULocationID': '114', 'DOLocationID': '236'},
 {'PULocationID': '137', 'DOLocationID': '79'},
 {'PULocationID': '90', 'DOLocationID': '231'},
 {'PULocationID': '125', 'DOLocationID': '68'},
 {'PULocationID': '68', 'DOLocationID': '142'},
 {'PULocationID': '141', 'DOLocationID': '236'},
 {'PULocationID': '236', 'DOLocationID': '140'},
 {'PULocationID': '140', 'DOLocationID': '41'},
 {'PULocationID': '170', 'DOLocationID': '170'},
 {'PULocationID': '90', 'DOLocationID': '142'},
 {'PULocationID': '148', 'DOLocationID': '225'},
 {'PULocationID': '237', 'DOLocationID': '7'},
 {'PULocationID': '234', 'DOLocationID': '161'},
 {'PULocationID': '162', 'DOLocationID': '249'},
 {'PULocationID': '238', 'DOLocationID': '166'},
 {'PULocationID': '43', 'DOLocationID': '238'},
 {'PULocationID': '162', 'DOLocationID': '233'},
 {'PULocationID': '237', 'DOLocationID': '141'},
 {'PULocationID': '141', 'DOLocationID': '262'},
 {'PULocationID': '236', 'DOLocationID': '143'},
 {'PULocationID': '239', 'DOLocationID': '236'},
 {'PULocationID': '68', 'DOLocationID': '236'},
 {'PULocationID': '142', 'DOLocationID': '50'},
 {'PULocationID': '79', 'DOLocationID': '161'},
 {'PULocationID': '237', 'DOLocationID': '237'},
 {'PULocationID': '237', 'DOLocationID': '24'},
 {'PULocationID': '107', 'DOLocationID': '170'},
 {'PULocationID': '162', 'DOLocationID': '262'},
 {'PULocationID': '263', 'DOLocationID': '140'},
 {'PULocationID': '229', 'DOLocationID': '170'},
 {'PULocationID': '144', 'DOLocationID': '233'},
 {'PULocationID': '233', 'DOLocationID': '144'},
 {'PULocationID': '90', 'DOLocationID': '249'},
 {'PULocationID': '249', 'DOLocationID': '233'},
 {'PULocationID': '90', 'DOLocationID': '79'},
 {'PULocationID': '161', 'DOLocationID': '68'},
 {'PULocationID': '263', 'DOLocationID': '140'},
 {'PULocationID': '140', 'DOLocationID': '263'},
 {'PULocationID': '263', 'DOLocationID': '141'},
 {'PULocationID': '224', 'DOLocationID': '238'},
 {'PULocationID': '4', 'DOLocationID': '137'},
 {'PULocationID': '43', 'DOLocationID': '229'},
 {'PULocationID': '161', 'DOLocationID': '236'},
 {'PULocationID': '236', 'DOLocationID': '237'},
 {'PULocationID': '114', 'DOLocationID': '68'},
 {'PULocationID': '68', 'DOLocationID': '239'},
 {'PULocationID': '239', 'DOLocationID': '237'},
 {'PULocationID': '237', 'DOLocationID': '162'},
 {'PULocationID': '234', 'DOLocationID': '79'},
 {'PULocationID': '236', 'DOLocationID': '262'},
 {'PULocationID': '75', 'DOLocationID': '233'},
 {'PULocationID': '229', 'DOLocationID': '229'},
 {'PULocationID': '79', 'DOLocationID': '229'},
 {'PULocationID': '239', 'DOLocationID': '236'},
 {'PULocationID': '239', 'DOLocationID': '237'},
 {'PULocationID': '79', 'DOLocationID': '79'},
 {'PULocationID': '237', 'DOLocationID': '24'},
 {'PULocationID': '151', 'DOLocationID': '238'},
 {'PULocationID': '79', 'DOLocationID': '249'},
 {'PULocationID': '79', 'DOLocationID': '79'},
 {'PULocationID': '79', 'DOLocationID': '249'},
 {'PULocationID': '249', 'DOLocationID': '234'},
 {'PULocationID': '170', 'DOLocationID': '148'},
 {'PULocationID': '148', 'DOLocationID': '137'},
 {'PULocationID': '161', 'DOLocationID': '142'},
 {'PULocationID': '142', 'DOLocationID': '186'},
 {'PULocationID': '114', 'DOLocationID': '137'},
 {'PULocationID': '229', 'DOLocationID': '262'},
 {'PULocationID': '262', 'DOLocationID': '262'},
 {'PULocationID': '24', 'DOLocationID': '238'},
 {'PULocationID': '238', 'DOLocationID': '24'},
 {'PULocationID': '151', 'DOLocationID': '238'},
 {'PULocationID': '239', 'DOLocationID': '41'},
 {'PULocationID': '41', 'DOLocationID': '236'},
 {'PULocationID': '79', 'DOLocationID': '229'},
 {'PULocationID': '246', 'DOLocationID': '162'},
 {'PULocationID': '48', 'DOLocationID': '142'},
 {'PULocationID': '142', 'DOLocationID': '48'},
 {'PULocationID': '261', 'DOLocationID': '88'},
 {'PULocationID': '107', 'DOLocationID': '170'},
 {'PULocationID': '170', 'DOLocationID': '79'},
 {'PULocationID': '170', 'DOLocationID': '79'},
 {'PULocationID': '263', 'DOLocationID': '236'},
 {'PULocationID': '142', 'DOLocationID': '151'},
 {'PULocationID': '233', 'DOLocationID': '107'},
 {'PULocationID': '263', 'DOLocationID': '238'},
 {'PULocationID': '238', 'DOLocationID': '236'},
 {'PULocationID': '107', 'DOLocationID': '4'},
 {'PULocationID': '4', 'DOLocationID': '141'},
 {'PULocationID': '233', 'DOLocationID': '137'},
 {'PULocationID': '186', 'DOLocationID': '79'},
 {'PULocationID': '79', 'DOLocationID': '107'},
 {'PULocationID': '107', 'DOLocationID': '170'},
 {'PULocationID': '114', 'DOLocationID': '143'},
 {'PULocationID': '234', 'DOLocationID': '162'},
 {'PULocationID': '148', 'DOLocationID': '107'},
 {'PULocationID': '161', 'DOLocationID': '64'},
 {'PULocationID': '151', 'DOLocationID': '236'},
 {'PULocationID': '236', 'DOLocationID': '239'},
 {'PULocationID': '239', 'DOLocationID': '239'},
 {'PULocationID': '239', 'DOLocationID': '140'},
 {'PULocationID': '87', 'DOLocationID': '90'},
 {'PULocationID': '249', 'DOLocationID': '170'},
 {'PULocationID': '144', 'DOLocationID': '263'},
 {'PULocationID': '142', 'DOLocationID': '68'},
 {'PULocationID': '186', 'DOLocationID': '113'},
 {'PULocationID': '113', 'DOLocationID': '33'},
 {'PULocationID': '138', 'DOLocationID': '188'},
 {'PULocationID': '262', 'DOLocationID': '90'},
 {'PULocationID': '246', 'DOLocationID': '4'},
 {'PULocationID': '68', 'DOLocationID': '107'},
 {'PULocationID': '234', 'DOLocationID': '239'},
 {'PULocationID': '186', 'DOLocationID': '137'},
 {'PULocationID': '236', 'DOLocationID': '142'},
 {'PULocationID': '142', 'DOLocationID': '233'},
 {'PULocationID': '237', 'DOLocationID': '263'},
 {'PULocationID': '163', 'DOLocationID': '232'},
 {'PULocationID': '144', 'DOLocationID': '148'},
 {'PULocationID': '79', 'DOLocationID': '80'},
 {'PULocationID': '246', 'DOLocationID': '48'},
 {'PULocationID': '249', 'DOLocationID': '144'},
 {'PULocationID': '137', 'DOLocationID': '231'},
 {'PULocationID': '90', 'DOLocationID': '79'},
 {'PULocationID': '107', 'DOLocationID': '237'},
 {'PULocationID': '137', 'DOLocationID': '50'},
 {'PULocationID': '164', 'DOLocationID': '142'},
 {'PULocationID': '236', 'DOLocationID': '143'},
 {'PULocationID': '143', 'DOLocationID': '237'},
 {'PULocationID': '237', 'DOLocationID': '234'},
 {'PULocationID': '79', 'DOLocationID': '263'},
 {'PULocationID': '238', 'DOLocationID': '237'},
 {'PULocationID': '142', 'DOLocationID': '262'},
 {'PULocationID': '142', 'DOLocationID': '141'},
 {'PULocationID': '239', 'DOLocationID': '236'},
 {'PULocationID': '170', 'DOLocationID': '233'},
 {'PULocationID': '237', 'DOLocationID': '262'},
 {'PULocationID': '263', 'DOLocationID': '263'},
 {'PULocationID': '79', 'DOLocationID': '231'},
 {'PULocationID': '164', 'DOLocationID': '233'},
 {'PULocationID': '263', 'DOLocationID': '50'},
 {'PULocationID': '238', 'DOLocationID': '239'},
 {'PULocationID': '50', 'DOLocationID': '246'},
 {'PULocationID': '68', 'DOLocationID': '90'},
 {'PULocationID': '90', 'DOLocationID': '249'},
 {'PULocationID': '90', 'DOLocationID': '229'},
 {'PULocationID': '161', 'DOLocationID': '261'},
 {'PULocationID': '231', 'DOLocationID': '40'},
 {'PULocationID': '50', 'DOLocationID': '40'},
 {'PULocationID': '114', 'DOLocationID': '231'},
 {'PULocationID': '231', 'DOLocationID': '43'},
 {'PULocationID': '163', 'DOLocationID': '143'},
 {'PULocationID': '143', 'DOLocationID': '236'},
 {'PULocationID': '107', 'DOLocationID': '234'},
 {'PULocationID': '68', 'DOLocationID': '142'},
 {'PULocationID': '142', 'DOLocationID': '224'},
 {'PULocationID': '158', 'DOLocationID': '164'},
 {'PULocationID': '234', 'DOLocationID': '140'},
 {'PULocationID': '43', 'DOLocationID': '170'},
 {'PULocationID': '161', 'DOLocationID': '137'},
 {'PULocationID': '140', 'DOLocationID': '238'},
 {'PULocationID': '263', 'DOLocationID': '42'},
 {'PULocationID': '132', 'DOLocationID': '87'},
 {'PULocationID': '107', 'DOLocationID': '170'},
 {'PULocationID': '114', 'DOLocationID': '107'},
 {'PULocationID': '48', 'DOLocationID': '142'},
 {'PULocationID': '43', 'DOLocationID': '141'},
 {'PULocationID': '237', 'DOLocationID': '229'},
 {'PULocationID': '262', 'DOLocationID': '202'},
 {'PULocationID': '237', 'DOLocationID': '236'},
 {'PULocationID': '249', 'DOLocationID': '88'},
 {'PULocationID': '88', 'DOLocationID': '232'},
 {'PULocationID': '114', 'DOLocationID': '74'},
 {'PULocationID': '237', 'DOLocationID': '263'},
 {'PULocationID': '236', 'DOLocationID': '238'},
 {'PULocationID': '249', 'DOLocationID': '249'},
 {'PULocationID': '114', 'DOLocationID': '79'},
 {'PULocationID': '79', 'DOLocationID': '238'},
 {'PULocationID': '79', 'DOLocationID': '170'},
 {'PULocationID': '233', 'DOLocationID': '107'},
 {'PULocationID': '137', 'DOLocationID': '145'},
 {'PULocationID': '263', 'DOLocationID': '262'},
 {'PULocationID': '263', 'DOLocationID': '229'},
 {'PULocationID': '263', 'DOLocationID': '50'},
 {'PULocationID': '249', 'DOLocationID': '249'},
 {'PULocationID': '125', 'DOLocationID': '164'},
 {'PULocationID': '161', 'DOLocationID': '211'},
 {'PULocationID': '186', 'DOLocationID': '141'},
 {'PULocationID': '162', 'DOLocationID': '50'},
 {'PULocationID': '237', 'DOLocationID': '237'},
 {'PULocationID': '237', 'DOLocationID': '141'},
 {'PULocationID': '237', 'DOLocationID': '166'},
 {'PULocationID': '236', 'DOLocationID': '140'},
 {'PULocationID': '140', 'DOLocationID': '114'},
 {'PULocationID': '114', 'DOLocationID': '140'},
 {'PULocationID': '170', 'DOLocationID': '261'},
 {'PULocationID': '261', 'DOLocationID': '68'},
 {'PULocationID': '249', 'DOLocationID': '68'},
 {'PULocationID': '249', 'DOLocationID': '186'},
 {'PULocationID': '141', 'DOLocationID': '75'},
 {'PULocationID': '141', 'DOLocationID': '87'},
 {'PULocationID': '87', 'DOLocationID': '232'},
 {'PULocationID': '114', 'DOLocationID': '170'},
 {'PULocationID': '162', 'DOLocationID': '141'},
 {'PULocationID': '161', 'DOLocationID': '236'},
 {'PULocationID': '143', 'DOLocationID': '143'},
 {'PULocationID': '79', 'DOLocationID': '66'},
 {'PULocationID': '234', 'DOLocationID': '164'},
 {'PULocationID': '4', 'DOLocationID': '107'},
 {'PULocationID': '229', 'DOLocationID': '161'},
 {'PULocationID': '234', 'DOLocationID': '170'},
 {'PULocationID': '137', 'DOLocationID': '229'},
 {'PULocationID': '158', 'DOLocationID': '186'},
 {'PULocationID': '164', 'DOLocationID': '68'},
 {'PULocationID': '158', 'DOLocationID': '261'},
 {'PULocationID': '229', 'DOLocationID': '233'},
 {'PULocationID': '239', 'DOLocationID': '24'},
 {'PULocationID': '239', 'DOLocationID': '151'},
 {'PULocationID': '163', 'DOLocationID': '170'},
 {'PULocationID': '114', 'DOLocationID': '239'},
 {'PULocationID': '132', 'DOLocationID': '79'},
 {'PULocationID': '41', 'DOLocationID': '41'},
 {'PULocationID': '41', 'DOLocationID': '238'},
 {'PULocationID': '238', 'DOLocationID': '140'},
 {'PULocationID': '141', 'DOLocationID': '233'},
 {'PULocationID': '148', 'DOLocationID': '237'},
 {'PULocationID': '236', 'DOLocationID': '263'},
 {'PULocationID': '141', 'DOLocationID': '237'},
 {'PULocationID': '148', 'DOLocationID': '107'},
 {'PULocationID': '48', 'DOLocationID': '265'},
 {'PULocationID': '237', 'DOLocationID': '141'},
 {'PULocationID': '239', 'DOLocationID': '24'},
 {'PULocationID': '114', 'DOLocationID': '170'},
 {'PULocationID': '143', 'DOLocationID': '263'},
 {'PULocationID': '263', 'DOLocationID': '75'},
 {'PULocationID': '68', 'DOLocationID': '158'},
 {'PULocationID': '125', 'DOLocationID': '262'},
 {'PULocationID': '107', 'DOLocationID': '232'},
 {'PULocationID': '249', 'DOLocationID': '79'},
 {'PULocationID': '107', 'DOLocationID': '234'},
 {'PULocationID': '236', 'DOLocationID': '238'},
 {'PULocationID': '239', 'DOLocationID': '143'},
 {'PULocationID': '142', 'DOLocationID': '238'},
 {'PULocationID': '238', 'DOLocationID': '239'},
 {'PULocationID': '239', 'DOLocationID': '166'},
 {'PULocationID': '161', 'DOLocationID': '170'},
 {'PULocationID': '233', 'DOLocationID': '189'},
 {'PULocationID': '107', 'DOLocationID': '137'},

In [18]:
dict = DictVectorizer()
x_train = dict.fit_transform(train_dict)
y_train = df.duration.values

In [19]:
Q4 = x_train
Q4

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 7143848 stored elements and shape (3571924, 521)>

In [20]:
lr = LinearRegression()
lr.fit(x_train, y_train)
y_pred = lr.predict(x_train)
rmse = root_mean_squared_error(y_train, y_pred)

In [21]:
Q5 = rmse

In [22]:
Q5

8.989025860177977

In [23]:
df_val = pd.read_parquet(filename_feb)

In [24]:
df_val.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,7,2026-02-01 00:05:57,2026-02-01 00:05:57,1.0,0.94,1.0,N,107,170,1,7.2,0.00,0.5,0.00,0.0,1.0,12.95,2.5,0.00,0.75
1,7,2026-02-01 00:35:58,2026-02-01 00:35:58,1.0,1.93,1.0,N,234,141,1,11.4,0.00,0.5,3.43,0.0,1.0,20.58,2.5,0.00,0.75
2,2,2026-02-01 00:08:41,2026-02-01 00:39:32,1.0,9.99,1.0,N,138,68,1,44.3,6.00,0.5,11.01,0.0,1.0,67.81,2.5,1.75,0.75
3,1,2026-02-01 00:29:06,2026-02-01 00:41:04,0.0,1.70,1.0,N,209,13,1,12.8,4.25,0.5,3.70,0.0,1.0,22.25,2.5,0.00,0.75
4,1,2026-02-01 00:53:52,2026-02-01 01:11:21,0.0,3.70,1.0,N,249,229,1,19.8,4.25,0.5,6.35,0.0,1.0,31.90,2.5,0.00,0.75

In [25]:
df_val.tpep_dropoff_datetime = pd.to_datetime(df_val.tpep_dropoff_datetime)
df_val.tpep_pickup_datetime = pd.to_datetime(df_val.tpep_pickup_datetime)

df_val['duration'] = df_val.tpep_dropoff_datetime - df_val.tpep_pickup_datetime

df_val.duration = df_val.duration.apply( lambda td: td.total_seconds() / 60)

In [26]:
df_val.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,...,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee,duration
0,7,2026-02-01 00:05:57,2026-02-01 00:05:57,1.0,0.94,1.0,N,107,170,1,...,0.00,0.5,0.00,0.0,1.0,12.95,2.5,0.00,0.75,0.000000
1,7,2026-02-01 00:35:58,2026-02-01 00:35:58,1.0,1.93,1.0,N,234,141,1,...,0.00,0.5,3.43,0.0,1.0,20.58,2.5,0.00,0.75,0.000000
2,2,2026-02-01 00:08:41,2026-02-01 00:39:32,1.0,9.99,1.0,N,138,68,1,...,6.00,0.5,11.01,0.0,1.0,67.81,2.5,1.75,0.75,30.850000
3,1,2026-02-01 00:29:06,2026-02-01 00:41:04,0.0,1.70,1.0,N,209,13,1,...,4.25,0.5,3.70,0.0,1.0,22.25,2.5,0.00,0.75,11.966667
4,1,2026-02-01 00:53:52,2026-02-01 01:11:21,0.0,3.70,1.0,N,249,229,1,...,4.25,0.5,6.35,0.0,1.0,31.90,2.5,0.00,0.75,17.483333

In [27]:
df_val = df_val[((df_val.duration >= 1) & (df_val.duration <= 60))]
categorical = ['PULocationID', 'DOLocationID']
df_val[categorical] = df_val[categorical].astype(str)

val_dicts = df_val[categorical].to_dict(orient='records')

In [28]:
val_dicts

[{'PULocationID': '138', 'DOLocationID': '68'},
 {'PULocationID': '209', 'DOLocationID': '13'},
 {'PULocationID': '249', 'DOLocationID': '229'},
 {'PULocationID': '113', 'DOLocationID': '90'},
 {'PULocationID': '234', 'DOLocationID': '144'},
 {'PULocationID': '237', 'DOLocationID': '151'},
 {'PULocationID': '148', 'DOLocationID': '263'},
 {'PULocationID': '79', 'DOLocationID': '170'},
 {'PULocationID': '161', 'DOLocationID': '114'},
 {'PULocationID': '263', 'DOLocationID': '116'},
 {'PULocationID': '237', 'DOLocationID': '141'},
 {'PULocationID': '181', 'DOLocationID': '49'},
 {'PULocationID': '97', 'DOLocationID': '181'},
 {'PULocationID': '114', 'DOLocationID': '114'},
 {'PULocationID': '114', 'DOLocationID': '249'},
 {'PULocationID': '249', 'DOLocationID': '158'},
 {'PULocationID': '68', 'DOLocationID': '162'},
 {'PULocationID': '114', 'DOLocationID': '209'},
 {'PULocationID': '170', 'DOLocationID': '170'},
 {'PULocationID': '132', 'DOLocationID': '260'},
 {'PULocationID': '239', 'DOLocationID': '263'},
 {'PULocationID': '236', 'DOLocationID': '239'},
 {'PULocationID': '239', 'DOLocationID': '140'},
 {'PULocationID': '229', 'DOLocationID': '224'},
 {'PULocationID': '234', 'DOLocationID': '107'},
 {'PULocationID': '113', 'DOLocationID': '239'},
 {'PULocationID': '249', 'DOLocationID': '233'},
 {'PULocationID': '132', 'DOLocationID': '172'},
 {'PULocationID': '97', 'DOLocationID': '148'},
 {'PULocationID': '148', 'DOLocationID': '181'},
 {'PULocationID': '113', 'DOLocationID': '166'},
 {'PULocationID': '237', 'DOLocationID': '263'},
 {'PULocationID': '141', 'DOLocationID': '263'},
 {'PULocationID': '239', 'DOLocationID': '236'},
 {'PULocationID': '144', 'DOLocationID': '158'},
 {'PULocationID': '158', 'DOLocationID': '107'},
 {'PULocationID': '114', 'DOLocationID': '79'},
 {'PULocationID': '79', 'DOLocationID': '170'},
 {'PULocationID': '262', 'DOLocationID': '224'},
 {'PULocationID': '140', 'DOLocationID': '263'},
 {'PULocationID': '262', 'DOLocationID': '229'},
 {'PULocationID': '113', 'DOLocationID': '113'},
 {'PULocationID': '234', 'DOLocationID': '127'},
 {'PULocationID': '132', 'DOLocationID': '48'},
 {'PULocationID': '100', 'DOLocationID': '239'},
 {'PULocationID': '68', 'DOLocationID': '246'},
 {'PULocationID': '249', 'DOLocationID': '158'},
 {'PULocationID': '158', 'DOLocationID': '88'},
 {'PULocationID': '90', 'DOLocationID': '262'},
 {'PULocationID': '163', 'DOLocationID': '24'},
 {'PULocationID': '229', 'DOLocationID': '143'},
 {'PULocationID': '142', 'DOLocationID': '75'},
 {'PULocationID': '113', 'DOLocationID': '142'},
 {'PULocationID': '143', 'DOLocationID': '140'},
 {'PULocationID': '162', 'DOLocationID': '186'},
 {'PULocationID': '100', 'DOLocationID': '229'},
 {'PULocationID': '263', 'DOLocationID': '236'},
 {'PULocationID': '265', 'DOLocationID': '265'},
 {'PULocationID': '231', 'DOLocationID': '249'},
 {'PULocationID': '114', 'DOLocationID': '143'},
 {'PULocationID': '87', 'DOLocationID': '107'},
 {'PULocationID': '137', 'DOLocationID': '234'},
 {'PULocationID': '113', 'DOLocationID': '249'},
 {'PULocationID': '249', 'DOLocationID': '170'},
 {'PULocationID': '230', 'DOLocationID': '230'},
 {'PULocationID': '234', 'DOLocationID': '45'},
 {'PULocationID': '70', 'DOLocationID': '82'},
 {'PULocationID': '165', 'DOLocationID': '89'},
 {'PULocationID': '148', 'DOLocationID': '112'},
 {'PULocationID': '107', 'DOLocationID': '50'},
 {'PULocationID': '132', 'DOLocationID': '218'},
 {'PULocationID': '229', 'DOLocationID': '137'},
 {'PULocationID': '249', 'DOLocationID': '107'},
 {'PULocationID': '236', 'DOLocationID': '262'},
 {'PULocationID': '263', 'DOLocationID': '107'},
 {'PULocationID': '100', 'DOLocationID': '246'},
 {'PULocationID': '249', 'DOLocationID': '141'},
 {'PULocationID': '125', 'DOLocationID': '161'},
 {'PULocationID': '48', 'DOLocationID': '113'},
 {'PULocationID': '249', 'DOLocationID': '237'},
 {'PULocationID': '100', 'DOLocationID': '262'},
 {'PULocationID': '107', 'DOLocationID': '48'},
 {'PULocationID': '4', 'DOLocationID': '234'},
 {'PULocationID': '249', 'DOLocationID': '107'},
 {'PULocationID': '263', 'DOLocationID': '238'},
 {'PULocationID': '140', 'DOLocationID': '140'},
 {'PULocationID': '233', 'DOLocationID': '90'},
 {'PULocationID': '100', 'DOLocationID': '246'},
 {'PULocationID': '249', 'DOLocationID': '170'},
 {'PULocationID': '234', 'DOLocationID': '231'},
 {'PULocationID': '234', 'DOLocationID': '246'},
 {'PULocationID': '234', 'DOLocationID': '170'},
 {'PULocationID': '249', 'DOLocationID': '68'},
 {'PULocationID': '246', 'DOLocationID': '239'},
 {'PULocationID': '48', 'DOLocationID': '146'},
 {'PULocationID': '170', 'DOLocationID': '141'},
 {'PULocationID': '107', 'DOLocationID': '140'},
 {'PULocationID': '79', 'DOLocationID': '4'},
 {'PULocationID': '158', 'DOLocationID': '231'},
 {'PULocationID': '231', 'DOLocationID': '232'},
 {'PULocationID': '249', 'DOLocationID': '211'},
 {'PULocationID': '79', 'DOLocationID': '4'},
 {'PULocationID': '79', 'DOLocationID': '4'},
 {'PULocationID': '79', 'DOLocationID': '148'},
 {'PULocationID': '148', 'DOLocationID': '48'},
 {'PULocationID': '48', 'DOLocationID': '100'},
 {'PULocationID': '100', 'DOLocationID': '143'},
 {'PULocationID': '229', 'DOLocationID': '263'},
 {'PULocationID': '263', 'DOLocationID': '107'},
 {'PULocationID': '170', 'DOLocationID': '48'},
 {'PULocationID': '79', 'DOLocationID': '90'},
 {'PULocationID': '90', 'DOLocationID': '249'},
 {'PULocationID': '142', 'DOLocationID': '233'},
 {'PULocationID': '262', 'DOLocationID': '238'},
 {'PULocationID': '263', 'DOLocationID': '137'},
 {'PULocationID': '263', 'DOLocationID': '74'},
 {'PULocationID': '170', 'DOLocationID': '263'},
 {'PULocationID': '142', 'DOLocationID': '239'},
 {'PULocationID': '249', 'DOLocationID': '209'},
 {'PULocationID': '229', 'DOLocationID': '233'},
 {'PULocationID': '114', 'DOLocationID': '4'},
 {'PULocationID': '79', 'DOLocationID': '170'},
 {'PULocationID': '170', 'DOLocationID': '239'},
 {'PULocationID': '229', 'DOLocationID': '13'},
 {'PULocationID': '79', 'DOLocationID': '246'},
 {'PULocationID': '113', 'DOLocationID': '261'},
 {'PULocationID': '229', 'DOLocationID': '79'},
 {'PULocationID': '239', 'DOLocationID': '237'},
 {'PULocationID': '48', 'DOLocationID': '80'},
 {'PULocationID': '164', 'DOLocationID': '79'},
 {'PULocationID': '79', 'DOLocationID': '249'},
 {'PULocationID': '43', 'DOLocationID': '238'},
 {'PULocationID': '164', 'DOLocationID': '143'},
 {'PULocationID': '25', 'DOLocationID': '61'},
 {'PULocationID': '90', 'DOLocationID': '186'},
 {'PULocationID': '100', 'DOLocationID': '48'},
 {'PULocationID': '141', 'DOLocationID': '263'},
 {'PULocationID': '236', 'DOLocationID': '238'},
 {'PULocationID': '186', 'DOLocationID': '79'},
 {'PULocationID': '87', 'DOLocationID': '114'},
 {'PULocationID': '114', 'DOLocationID': '231'},
 {'PULocationID': '239', 'DOLocationID': '141'},
 {'PULocationID': '141', 'DOLocationID': '170'},
 {'PULocationID': '48', 'DOLocationID': '162'},
 {'PULocationID': '164', 'DOLocationID': '142'},
 {'PULocationID': '68', 'DOLocationID': '114'},
 {'PULocationID': '114', 'DOLocationID': '148'},
 {'PULocationID': '148', 'DOLocationID': '148'},
 {'PULocationID': '148', 'DOLocationID': '79'},
 {'PULocationID': '230', 'DOLocationID': '142'},
 {'PULocationID': '113', 'DOLocationID': '161'},
 {'PULocationID': '87', 'DOLocationID': '249'},
 {'PULocationID': '211', 'DOLocationID': '237'},
 {'PULocationID': '237', 'DOLocationID': '263'},
 {'PULocationID': '132', 'DOLocationID': '112'},
 {'PULocationID': '148', 'DOLocationID': '88'},
 {'PULocationID': '231', 'DOLocationID': '114'},
 {'PULocationID': '114', 'DOLocationID': '261'},
 {'PULocationID': '48', 'DOLocationID': '246'},
 {'PULocationID': '158', 'DOLocationID': '107'},
 {'PULocationID': '113', 'DOLocationID': '246'},
 {'PULocationID': '163', 'DOLocationID': '263'},
 {'PULocationID': '249', 'DOLocationID': '231'},
 {'PULocationID': '231', 'DOLocationID': '249'},
 {'PULocationID': '114', 'DOLocationID': '249'},
 {'PULocationID': '249', 'DOLocationID': '164'},
 {'PULocationID': '164', 'DOLocationID': '141'},
 {'PULocationID': '90', 'DOLocationID': '107'},
 {'PULocationID': '79', 'DOLocationID': '48'},
 {'PULocationID': '148', 'DOLocationID': '238'},
 {'PULocationID': '237', 'DOLocationID': '238'},
 {'PULocationID': '170', 'DOLocationID': '79'},
 {'PULocationID': '144', 'DOLocationID': '4'},
 {'PULocationID': '148', 'DOLocationID': '249'},
 {'PULocationID': '249', 'DOLocationID': '256'},
 {'PULocationID': '234', 'DOLocationID': '246'},
 {'PULocationID': '158', 'DOLocationID': '90'},
 {'PULocationID': '48', 'DOLocationID': '243'},
 {'PULocationID': '48', 'DOLocationID': '239'},
 {'PULocationID': '161', 'DOLocationID': '162'},
 {'PULocationID': '163', 'DOLocationID': '236'},
 {'PULocationID': '237', 'DOLocationID': '141'},
 {'PULocationID': '233', 'DOLocationID': '74'},
 {'PULocationID': '234', 'DOLocationID': '7'},
 {'PULocationID': '144', 'DOLocationID': '112'},
 {'PULocationID': '232', 'DOLocationID': '249'},
 {'PULocationID': '263', 'DOLocationID': '74'},
 {'PULocationID': '162', 'DOLocationID': '107'},
 {'PULocationID': '114', 'DOLocationID': '164'},
 {'PULocationID': '236', 'DOLocationID': '161'},
 {'PULocationID': '237', 'DOLocationID': '262'},
 {'PULocationID': '114', 'DOLocationID': '231'},
 {'PULocationID': '231', 'DOLocationID': '90'},
 {'PULocationID': '229', 'DOLocationID': '79'},
 {'PULocationID': '79', 'DOLocationID': '137'},
 {'PULocationID': '79', 'DOLocationID': '33'},
 {'PULocationID': '144', 'DOLocationID': '236'},
 {'PULocationID': '211', 'DOLocationID': '211'},
 {'PULocationID': '211', 'DOLocationID': '249'},
 {'PULocationID': '249', 'DOLocationID': '79'},
 {'PULocationID': '161', 'DOLocationID': '170'},
 {'PULocationID': '141', 'DOLocationID': '140'},
 {'PULocationID': '161', 'DOLocationID': '161'},
 {'PULocationID': '161', 'DOLocationID': '161'},
 {'PULocationID': '107', 'DOLocationID': '79'},
 {'PULocationID': '249', 'DOLocationID': '79'},
 {'PULocationID': '114', 'DOLocationID': '143'},
 {'PULocationID': '138', 'DOLocationID': '164'},
 {'PULocationID': '164', 'DOLocationID': '141'},
 {'PULocationID': '43', 'DOLocationID': '229'},
 {'PULocationID': '263', 'DOLocationID': '41'},
 {'PULocationID': '249', 'DOLocationID': '170'},
 {'PULocationID': '79', 'DOLocationID': '90'},
 {'PULocationID': '137', 'DOLocationID': '107'},
 {'PULocationID': '87', 'DOLocationID': '164'},
 {'PULocationID': '114', 'DOLocationID': '141'},
 {'PULocationID': '229', 'DOLocationID': '68'},
 {'PULocationID': '125', 'DOLocationID': '148'},
 {'PULocationID': '125', 'DOLocationID': '148'},
 {'PULocationID': '164', 'DOLocationID': '262'},
 {'PULocationID': '90', 'DOLocationID': '107'},
 {'PULocationID': '249', 'DOLocationID': '113'},
 {'PULocationID': '107', 'DOLocationID': '79'},
 {'PULocationID': '79', 'DOLocationID': '79'},
 {'PULocationID': '231', 'DOLocationID': '90'},
 {'PULocationID': '249', 'DOLocationID': '231'},
 {'PULocationID': '229', 'DOLocationID': '163'},
 {'PULocationID': '100', 'DOLocationID': '95'},
 {'PULocationID': '249', 'DOLocationID': '68'},
 {'PULocationID': '68', 'DOLocationID': '158'},
 {'PULocationID': '79', 'DOLocationID': '79'},
 {'PULocationID': '249', 'DOLocationID': '141'},
 {'PULocationID': '263', 'DOLocationID': '79'},
 {'PULocationID': '79', 'DOLocationID': '144'},
 {'PULocationID': '144', 'DOLocationID': '231'},
 {'PULocationID': '230', 'DOLocationID': '230'},
 {'PULocationID': '48', 'DOLocationID': '239'},
 {'PULocationID': '237', 'DOLocationID': '161'},
 {'PULocationID': '230', 'DOLocationID': '142'},
 {'PULocationID': '48', 'DOLocationID': '238'},
 {'PULocationID': '113', 'DOLocationID': '181'},
 {'PULocationID': '114', 'DOLocationID': '231'},
 {'PULocationID': '231', 'DOLocationID': '79'},
 {'PULocationID': '79', 'DOLocationID': '239'},
 {'PULocationID': '68', 'DOLocationID': '142'},
 {'PULocationID': '48', 'DOLocationID': '229'},
 {'PULocationID': '148', 'DOLocationID': '238'},
 {'PULocationID': '166', 'DOLocationID': '143'},
 {'PULocationID': '249', 'DOLocationID': '114'},
 {'PULocationID': '107', 'DOLocationID': '114'},
 {'PULocationID': '79', 'DOLocationID': '87'},
 {'PULocationID': '209', 'DOLocationID': '231'},
 {'PULocationID': '211', 'DOLocationID': '229'},
 {'PULocationID': '114', 'DOLocationID': '232'},
 {'PULocationID': '68', 'DOLocationID': '79'},
 {'PULocationID': '79', 'DOLocationID': '45'},
 {'PULocationID': '148', 'DOLocationID': '137'},
 {'PULocationID': '68', 'DOLocationID': '170'},
 {'PULocationID': '161', 'DOLocationID': '224'},
 {'PULocationID': '107', 'DOLocationID': '236'},
 {'PULocationID': '229', 'DOLocationID': '141'},
 {'PULocationID': '141', 'DOLocationID': '143'},
 {'PULocationID': '48', 'DOLocationID': '50'},
 {'PULocationID': '186', 'DOLocationID': '233'},
 {'PULocationID': '237', 'DOLocationID': '236'},
 {'PULocationID': '137', 'DOLocationID': '151'},
 {'PULocationID': '230', 'DOLocationID': '164'},
 {'PULocationID': '100', 'DOLocationID': '239'},
 {'PULocationID': '113', 'DOLocationID': '113'},
 {'PULocationID': '113', 'DOLocationID': '68'},
 {'PULocationID': '90', 'DOLocationID': '143'},
 {'PULocationID': '4', 'DOLocationID': '137'},
 {'PULocationID': '148', 'DOLocationID': '236'},
 {'PULocationID': '142', 'DOLocationID': '142'},
 {'PULocationID': '142', 'DOLocationID': '239'},
 {'PULocationID': '239', 'DOLocationID': '237'},
 {'PULocationID': '237', 'DOLocationID': '148'},
 {'PULocationID': '107', 'DOLocationID': '148'},
 {'PULocationID': '143', 'DOLocationID': '239'},
 {'PULocationID': '48', 'DOLocationID': '142'},
 {'PULocationID': '164', 'DOLocationID': '100'},
 {'PULocationID': '249', 'DOLocationID': '79'},
 {'PULocationID': '79', 'DOLocationID': '229'},
 {'PULocationID': '148', 'DOLocationID': '4'},
 {'PULocationID': '239', 'DOLocationID': '142'},
 {'PULocationID': '48', 'DOLocationID': '48'},
 {'PULocationID': '170', 'DOLocationID': '87'},
 {'PULocationID': '48', 'DOLocationID': '239'},
 {'PULocationID': '249', 'DOLocationID': '234'},
 {'PULocationID': '132', 'DOLocationID': '151'},
 {'PULocationID': '231', 'DOLocationID': '249'},
 {'PULocationID': '141', 'DOLocationID': '249'},
 {'PULocationID': '68', 'DOLocationID': '230'},
 {'PULocationID': '230', 'DOLocationID': '263'},
 {'PULocationID': '68', 'DOLocationID': '114'},
 {'PULocationID': '114', 'DOLocationID': '137'},
 {'PULocationID': '107', 'DOLocationID': '80'},
 {'PULocationID': '48', 'DOLocationID': '229'},
 {'PULocationID': '144', 'DOLocationID': '162'},
 {'PULocationID': '79', 'DOLocationID': '186'},
 {'PULocationID': '79', 'DOLocationID': '186'},
 {'PULocationID': '263', 'DOLocationID': '233'},
 {'PULocationID': '148', 'DOLocationID': '164'},
 {'PULocationID': '164', 'DOLocationID': '164'},
 {'PULocationID': '249', 'DOLocationID': '170'},
 {'PULocationID': '238', 'DOLocationID': '243'},
 {'PULocationID': '43', 'DOLocationID': '249'},
 {'PULocationID': '249', 'DOLocationID': '148'},
 {'PULocationID': '79', 'DOLocationID': '232'},
 {'PULocationID': '79', 'DOLocationID': '90'},
 {'PULocationID': '249', 'DOLocationID': '263'},
 {'PULocationID': '236', 'DOLocationID': '211'},
 {'PULocationID': '144', 'DOLocationID': '90'},
 {'PULocationID': '107', 'DOLocationID': '237'},
 {'PULocationID': '79', 'DOLocationID': '162'},
 {'PULocationID': '211', 'DOLocationID': '68'},
 {'PULocationID': '249', 'DOLocationID': '151'},
 {'PULocationID': '48', 'DOLocationID': '48'},
 {'PULocationID': '249', 'DOLocationID': '107'},
 {'PULocationID': '113', 'DOLocationID': '148'},
 {'PULocationID': '148', 'DOLocationID': '140'},
 {'PULocationID': '162', 'DOLocationID': '237'},
 {'PULocationID': '137', 'DOLocationID': '148'},
 {'PULocationID': '148', 'DOLocationID': '234'},
 {'PULocationID': '48', 'DOLocationID': '140'},
 {'PULocationID': '79', 'DOLocationID': '231'},
 {'PULocationID': '170', 'DOLocationID': '140'},
 {'PULocationID': '249', 'DOLocationID': '90'},
 {'PULocationID': '249', 'DOLocationID': '113'},
 {'PULocationID': '113', 'DOLocationID': '75'},
 {'PULocationID': '238', 'DOLocationID': '42'},
 {'PULocationID': '162', 'DOLocationID': '230'},
 {'PULocationID': '263', 'DOLocationID': '170'},
 {'PULocationID': '249', 'DOLocationID': '113'},
 {'PULocationID': '113', 'DOLocationID': '162'},
 {'PULocationID': '230', 'DOLocationID': '233'},
 {'PULocationID': '249', 'DOLocationID': '239'},
 {'PULocationID': '107', 'DOLocationID': '141'},
 {'PULocationID': '234', 'DOLocationID': '239'},
 {'PULocationID': '230', 'DOLocationID': '239'},
 {'PULocationID': '231', 'DOLocationID': '79'},
 {'PULocationID': '114', 'DOLocationID': '87'},
 {'PULocationID': '234', 'DOLocationID': '125'},
 {'PULocationID': '230', 'DOLocationID': '170'},
 {'PULocationID': '230', 'DOLocationID': '233'},
 {'PULocationID': '79', 'DOLocationID': '249'},
 {'PULocationID': '249', 'DOLocationID': '90'},
 {'PULocationID': '90', 'DOLocationID': '144'},
 {'PULocationID': '79', 'DOLocationID': '234'},
 {'PULocationID': '90', 'DOLocationID': '230'},
 {'PULocationID': '50', 'DOLocationID': '237'},
 {'PULocationID': '79', 'DOLocationID': '114'},
 {'PULocationID': '114', 'DOLocationID': '140'},
 {'PULocationID': '148', 'DOLocationID': '234'},
 {'PULocationID': '249', 'DOLocationID': '211'},
 {'PULocationID': '164', 'DOLocationID': '263'},
 {'PULocationID': '249', 'DOLocationID': '164'},
 {'PULocationID': '158', 'DOLocationID': '144'},
 {'PULocationID': '114', 'DOLocationID': '236'},
 {'PULocationID': '244', 'DOLocationID': '116'},
 {'PULocationID': '249', 'DOLocationID': '186'},
 {'PULocationID': '237', 'DOLocationID': '239'},
 {'PULocationID': '125', 'DOLocationID': '231'},
 {'PULocationID': '231', 'DOLocationID': '113'},
 {'PULocationID': '249', 'DOLocationID': '79'},
 {'PULocationID': '164', 'DOLocationID': '244'},
 {'PULocationID': '186', 'DOLocationID': '162'},
 {'PULocationID': '162', 'DOLocationID': '140'},
 {'PULocationID': '236', 'DOLocationID': '263'},
 {'PULocationID': '263', 'DOLocationID': '141'},
 {'PULocationID': '211', 'DOLocationID': '143'},
 {'PULocationID': '100', 'DOLocationID': '100'},
 {'PULocationID': '137', 'DOLocationID': '162'},
 {'PULocationID': '13', 'DOLocationID': '195'},
 {'PULocationID': '13', 'DOLocationID': '195'},
 {'PULocationID': '48', 'DOLocationID': '238'},
 {'PULocationID': '239', 'DOLocationID': '50'},
 {'PULocationID': '48', 'DOLocationID': '238'},
 {'PULocationID': '239', 'DOLocationID': '142'},
 {'PULocationID': '148', 'DOLocationID': '107'},
 {'PULocationID': '144', 'DOLocationID': '48'},
 {'PULocationID': '68', 'DOLocationID': '158'},
 {'PULocationID': '68', 'DOLocationID': '236'},
 {'PULocationID': '107', 'DOLocationID': '249'},
 {'PULocationID': '141', 'DOLocationID': '74'},
 {'PULocationID': '142', 'DOLocationID': '43'},
 {'PULocationID': '48', 'DOLocationID': '50'},
 {'PULocationID': '234', 'DOLocationID': '4'},
 {'PULocationID': '79', 'DOLocationID': '33'},
 {'PULocationID': '100', 'DOLocationID': '262'},
 {'PULocationID': '211', 'DOLocationID': '158'},
 {'PULocationID': '249', 'DOLocationID': '170'},
 {'PULocationID': '107', 'DOLocationID': '90'},
 {'PULocationID': '249', 'DOLocationID': '75'},
 {'PULocationID': '148', 'DOLocationID': '88'},
 {'PULocationID': '211', 'DOLocationID': '229'},
 {'PULocationID': '239', 'DOLocationID': '41'},
 {'PULocationID': '263', 'DOLocationID': '141'},
 {'PULocationID': '230', 'DOLocationID': '68'},
 {'PULocationID': '87', 'DOLocationID': '41'},
 {'PULocationID': '164', 'DOLocationID': '236'},
 {'PULocationID': '114', 'DOLocationID': '163'},
 {'PULocationID': '163', 'DOLocationID': '263'},
 {'PULocationID': '232', 'DOLocationID': '100'},
 {'PULocationID': '237', 'DOLocationID': '237'},
 {'PULocationID': '237', 'DOLocationID': '263'},
 {'PULocationID': '237', 'DOLocationID': '163'},
 {'PULocationID': '231', 'DOLocationID': '68'},
 {'PULocationID': '249', 'DOLocationID': '4'},
 {'PULocationID': '4', 'DOLocationID': '148'},
 {'PULocationID': '231', 'DOLocationID': '112'},
 {'PULocationID': '263', 'DOLocationID': '100'},

In [29]:
x_val = dict.transform(val_dicts)
y_val = df_val.duration.values
y_pred = lr.predict(x_val)
rmse = root_mean_squared_error(y_val, y_pred)

In [30]:
rmse

9.289483087304598